
name: 'pageup_dbt_utils'
version: '0.1'

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models: {}

on-run-start:
  - "{{ pageup_dbt_utils.create_audit_schema() }}"
  - "{{ pageup_dbt_utils.create_execution_log_table() }}"
  - "{{ pageup_dbt_utils.create_execution_model_log_table() }}"
  - "{{ pageup_dbt_utils.log_execution_start_event() }}"


on-run-end:
  - "{{ pageup_dbt_utils.log_execution_end_event() }}"
