
name: 'pageup_dbt_utils_integration_tests'
version: '1.0'

profile: 'default'

source-paths: ["fixtures"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target" 
clean-targets:        
    - "target"
    - "dbt_modules"

seeds:
    pageup_dbt_utils_integration_tests:
        load:
            schema: load
        expectations:
            schema: expectation

models:
    pageup_dbt_utils_integration_tests:
        schema: fixture
        materialized: table